name: Test on Linux
on: [pull_request, push]
jobs:
  test_on_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi-lib: [libopenmpi-dev, libmpich-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Install libraries
        run: |
          sudo apt-get update -y && sudo apt-get install -y build-essential ${{ matrix.mpi-lib }}
      - name: Run tests
        env:
          MSGPASS_USE_MPICH: 1
        run: |
          bash run-tests.bash

