name: Test on Linux
on: [pull_request, push]
jobs:
  test_on_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mpi_lib: libopenmpi-dev
            flag: 0
          - mpi_lib: libmpich-dev
            flag: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install libraries
        run: |
          sudo apt-get update -y && sudo apt-get install -y build-essential ${{ matrix.mpi_lib }}
      - name: Run tests
        run: |
          export MSGPASS_USE_MPICH=${{ matrix.flag }}
          bash run-tests.bash
