name: Test on macOS
on: [pull_request]
jobs:
  test_on_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure environment
        run: |
          echo TMPDIR=/tmp | tee -a $GITHUB_ENV
          env
      - name: Install LLVM
        run: |
          brew install llvm
      - name: Install OpenMPI
        run: |
          brew install open-mpi
      - name: Run tests
        run: |
          find / -iname "mpi.h"
          find / -iname "*mpi.so*"
          bash run-tests.bash

