name: Test on Windows
on: [pull_request, push]
jobs:
  test_on_windows:
    runs-on: windows-latest
    steps:
      - name: download MS-MPI setup
        run: curl -L -O https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe

      - name: Install mpiexec.exe (-force needed to bypass GUI on headless)
        run: .\msmpisetup.exe -unattend -force

      - name: test that mpiexec.exe exists
        # can't use MSMPI_BIN as Actions doesn't update PATH from msmpisetup.exe
        run: Test-Path "C:\Program Files\Microsoft MPI\Bin\mpiexec.exe" -PathType leaf

      - name: put MSMPI_BIN on PATH (where mpiexec is)
        run: echo "C:\Program Files\Microsoft MPI\Bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
