name: Test on macOS
on: [pull_request]
jobs:
  test_on_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libraries
        run: |
          brew install llvm open-mpi
          echo TMPDIR=/tmp | tee -a $GITHUB_ENV
          env
      - name: Run tests
        run: |
          bash run-tests.bash

