name: Test on Linux
on: [pull_request, push]
jobs:
  test_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libraries
        run: |
          sudo apt-get update -y && sudo apt-get install -y build-essential libopenmpi-dev
      - name: Run tests
        run: |
          bash run-tests.bash

